language: go
os:
    - linux
    - osx
go:
    - 1.13.x

before_install:
    - go get -t -v ./...

install:
    - go get github.com/xtaci/gaio

script:
    - go test -coverprofile=coverage.txt -covermode=atomic -v -bench .

after_success:
    - bash <(curl -s https://codecov.io/bash)
